### ISSUE TITLE
关于屏幕方向的问题

### ISSUE THREAD

**Issue by itcbx** [Co2333/iLrcOverlay#10]
我看了下hook springboard的代码，这里面手机默认是按竖屏状态来设置歌词显示的位置，默认在最下方，那么有个问题，如果现在不是在homescreen下，而是在某个可以横屏的应用里面，这个歌词显示位置就错了，是否有办法可以根据当前运行app的方向来确定歌词的位置？

**Comment by Lakr233** [comment]
已完结

在BigBoss更新之前 可以尝试从Release下载安装

**Comment by demo0102** [comment]
> 已完结
> 
> 在BigBoss更新之前 可以尝试从Release下载安装

感谢作者，体验很棒！
