### ISSUE TITLE
在ipad上使用的问题

### ISSUE THREAD

**Issue by 925070093** [Co2333/iLrcOverlay#2]
在ipad上，这个插件不能随屏幕旋转而改变方向。这个插件很棒，感谢。
On iPad, this plug-in cannot change direction as the screen rotates. This plugin is great, thanks.

**Comment by Lakr233** [comment]
你们丫从项目上线开始已经催了几百个人了

！！！！！！我还要高考，考完写。

**Comment by if1y** [comment]
期待一下，也是iPad横屏状态下的显示方向问题

**Comment by Lakr233** [comment]
> 期待一下，也是iPad横屏状态下的显示方向问题

那个是我设计成这样的。。。。。。。。。。。

下次加个选项吧

**Comment by itcbx** [comment]
这个和我最新发的那条类似，本身springboard的方向和当前运行app的方向可能是不一样的，貌似没有办法在springboard里获取当前app的显示方向，要设置横竖屏好像挺麻烦的

**Comment by demo0102** [comment]
> > 期待一下，也是iPad横屏状态下的显示方向问题
> 
> 那个是我设计成这样的。。。。。。。。。。。
> 
> 下次加个选项吧

大佬还在更新吗，ipad一般都是横屏用的，希望加上旋转屏幕歌词选项

**Comment by Lakr233** [comment]
> > > 期待一下，也是iPad横屏状态下的显示方向问题
> > 
> > 
> > 那个是我设计成这样的。。。。。。。。。。。
> > 下次加个选项吧
> 
> 大佬还在更新吗，ipad一般都是横屏用的，希望加上旋转屏幕歌词选项

这个我目前还没想到解决方案。。。。SpringBoard没有方向这个概念。。。

**Comment by demo0102** [comment]
> > > > 期待一下，也是iPad横屏状态下的显示方向问题
> > > 
> > > 
> > > 那个是我设计成这样的。。。。。。。。。。。
> > > 下次加个选项吧
> > 
> > 
> > 大佬还在更新吗，ipad一般都是横屏用的，希望加上旋转屏幕歌词选项
> 
> 这个我目前还没想到解决方案。。。。SpringBoard没有方向这个概念。。。

不如直接加个一直横屏的选项吧，越狱了用插件已经让所有应用都能横屏了

**Comment by Lakr233** [comment]
> 不如直接加个一直横屏的选项吧，越狱了用插件已经让所有应用都能横屏

问题比你想的复杂一些 不过我这段时间争取搞出来吧

**Comment by demo0102** [comment]
> > 不如直接加个一直横屏的选项吧，越狱了用插件已经让所有应用都能横屏
> 
> 问题比你想的复杂一些 不过我这段时间争取搞出来吧

好的，感谢大佬

**Comment by itcbx** [comment]
> > 不如直接加个一直横屏的选项吧，越狱了用插件已经让所有应用都能横屏
> 
> 问题比你想的复杂一些 不过我这段时间争取搞出来吧

我已经解决了

**Comment by Lakr233** [comment]
> > > 不如直接加个一直横屏的选项吧，越狱了用插件已经让所有应用都能横屏
> > 
> > 
> > 问题比你想的复杂一些 不过我这段时间争取搞出来吧
> 
> 我已经解决了

我也解决了 最近在调试一个崩溃

**Comment by Lakr233** [comment]
已完结

在BigBoss更新之前 可以尝试从Release下载安装

**Comment by if1y** [comment]
unc0ver终于更新支持越狱了
今天尝试，方向还是竖屏，是我哪里操作姿势有误嘛…
BigBoss和release版本均尝试了 🤥

**Comment by Lakr233** [comment]
设置里面启用了吗

**Comment by if1y** [comment]
> 设置里面启用了吗

系统设置里吗？没找到有这个插件的栏目

**Comment by Lakr233** [comment]
> > 设置里面启用了吗
> 
> 系统设置里吗？没找到有这个插件的栏目

iOS14上面的preferenceloader可能存在问题吧 这我就不知道了 你排查一下看看

**Comment by if1y** [comment]
> > > 设置里面启用了吗
> > 
> > 
> > 系统设置里吗？没找到有这个插件的栏目
> 
> iOS14上面的preferenceloader可能存在问题吧 这我就不知道了 你排查一下看看

嗯嗯，已解决 👍
