### ISSUE TITLE
Hello, can you please put the window to the top position?

### ISSUE THREAD

**Issue by hazie79** [Co2333/iLrcOverlay#6]
Hello, can you please put the window to the top position?
thank you very much！

![image](https://user-images.githubusercontent.com/25102841/86552570-fa088880-bf7a-11ea-81da-fb456c20eca6.png)

**Comment by Lakr233** [comment]
I'll add some customization options later this month.

**Comment by Lakr233** [comment]
Done, before the BigBoss get updated, you can download from release tab.
