### ISSUE TITLE
此插件在网易云音乐7.2.10及以上的版本中不显示歌词

### ISSUE THREAD

**Issue by reF1nd** [Co2333/iLrcOverlay#7]
希望能够支持新的版本，感谢作者的付出

**Comment by Lakr233** [comment]
得等几天 我服务器这几天在维护

**Comment by Lakr233** [comment]
已修复。在大老板源更新之前可以先用这个救急。

[nmlrc.deb.zip](https://github.com/Co2333/iLrcOverlay/files/5077418/nmlrc.deb.zip)
