### ISSUE TITLE
提供选项切换字体到Hiragino？

### ISSUE THREAD

**Issue by CaiMiao** [Co2333/iLrcOverlay#8]
虽然有些日语歌莫名其妙给睿智歌词繁转简 大部分还是没啥问题的

**Comment by Lakr233** [comment]
这个需求确实可以 晚点整上

**Comment by Lakr233** [comment]
![IMG_1A1A7A1EFDE2-1](https://user-images.githubusercontent.com/25259084/97585762-77796c80-1a34-11eb-935f-8ddfcb26381d.jpeg)

整上了 请等待版本更新（
