### ISSUE TITLE
歌词插件3.0 IPX/ios13.5 QQ音乐正常显示,网易云不显示歌词,

### ISSUE THREAD

**Issue by Today-to-Lsp** [Co2333/iLrcOverlay#9]
歌词插件3.0 IPX/ios13.5 QQ音乐正常显示,网易云不显示歌词,

**Comment by Lakr233** [comment]
我擦 我今晚看看

**Comment by Lakr233** [comment]
这个我一直没能复现 你看下端口6996有没有被占用

**Comment by Ochikororo** [comment]
iphone SHH如何查看6996端口有无占用?具体的命令是?

**Comment by Ochikororo** [comment]
lsof -i
netstat -an 都查看不了
![image](https://user-images.githubusercontent.com/31529293/90506559-0fcab980-e187-11ea-81ce-de200771e7b7.png)

**Comment by 954455850** [comment]
![IMG_1176](https://user-images.githubusercontent.com/31529293/90517969-b66b8600-e198-11ea-83bc-7b82aa394394.PNG)
![IMG_1177](https://user-images.githubusercontent.com/31529293/90517973-b8354980-e198-11ea-8a3f-799c46f86edd.PNG)

**Comment by Ochikororo** [comment]
QQ音乐正常,网易云不显示

**Comment by Lakr233** [comment]
咋办呐 我这里不能复现啊
![IMG_074338DAA641-1](https://user-images.githubusercontent.com/25259084/91005532-b391ea80-e609-11ea-8b44-3557a78d28b7.jpeg)

**Comment by Lakr233** [comment]
Closing due to inactive.
